// Writes a real HTML file for every public route, plus robots.txt and
// sitemap.xml.
//
// Why this exists at all. The site is one JavaScript application behind a
// catch-all rewrite, so without this every URL would serve the same markup:
// one title, one description, and one link preview for the whole site.
// Google would eventually render the JavaScript and see the right title.
// The crawlers that matter most here would not. A Janazah notice is shared
// in a WhatsApp group far more often than it is found in a search, and
// WhatsApp, iMessage and the rest read the markup and never run a line of
// script. They must find the right title and description already there.
//
// So each route gets a copy of index.html with its own head, and the router
// serves the same application on top of it (vercel.json, firebase.json).
// The files are committed rather than built on deploy, because the host
// serves this repository as static files with no build step.
//
// The output is generated, never hand-edited: `npm run build:seo` rewrites
// it, and tests/seo.test.js fails if what is committed no longer matches
// what this would produce. That is what keeps twelve copies of one <head>
// from drifting apart.

import { readFileSync, writeFileSync, readdirSync, unlinkSync } from 'node:fs';
import { join } from 'node:path';
import { SITE, PAGES, indexablePages, socialLinks } from '../public/js/site.js';

const PUBLIC = 'public';
const SOURCE = join(PUBLIC, 'index.html');
// The head block every page carries sits between these two markers in
// index.html, and the generator replaces what is between them. Markers
// rather than "find the title and the description and splice": index.html is
// both the template and one of the outputs, so generating must be idempotent
// or a second run appends a second copy of every tag.
const OPEN = '<!-- seo:start -->';
const CLOSE = '<!-- seo:end -->';
const STAMP = '  <!-- Generated by scripts/build-seo.mjs from public/js/site.js. '
  + 'Do not edit by hand: run `npm run build:seo`. -->';

const escape = (value) => String(value)
  .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
  .replace(/"/g, '&quot;');

/** The file a route is served from. "/" keeps index.html. */
export const fileFor = (path) => (path === '/' ? 'index.html' : `${path.slice(1)}.html`);

/**
 * Organization and SoftwareApplication, once, on every page.
 *
 * Only fields that are true and visible on the site. No aggregateRating, no
 * review, no address, no founding date: inventing any of those to win a
 * richer search result would be a lie told in a machine-readable format,
 * and Google's own guidance is that structured data must match what the
 * page actually shows.
 */
function siteSchema() {
  const organization = {
    '@type': 'Organization',
    '@id': `${SITE.origin}/#organization`,
    name: SITE.name,
    url: `${SITE.origin}/`,
    description: SITE.tagline,
    logo: `${SITE.origin}/icon-512.png`,
  };
  const social = socialLinks().map((entry) => entry.url);
  if (social.length) organization.sameAs = social;

  return {
    '@context': 'https://schema.org',
    '@graph': [
      organization,
      {
        '@type': 'WebSite',
        '@id': `${SITE.origin}/#website`,
        name: SITE.name,
        url: `${SITE.origin}/`,
        publisher: { '@id': `${SITE.origin}/#organization` },
        inLanguage: 'en',
      },
      {
        // The site is the application: it runs in the browser, needs no
        // account to read notices, and costs nothing. All three are stated
        // on the pages themselves.
        '@type': 'SoftwareApplication',
        '@id': `${SITE.origin}/#app`,
        name: SITE.name,
        url: `${SITE.origin}/`,
        applicationCategory: 'LifestyleApplication',
        operatingSystem: 'Any modern web browser',
        description: SITE.tagline,
        publisher: { '@id': `${SITE.origin}/#organization` },
        offers: { '@type': 'Offer', price: '0', priceCurrency: 'CAD' },
      },
    ],
  };
}

/** Home > Section, for the pages that sit under the home page. */
function breadcrumbSchema(page) {
  if (!page.breadcrumb) return null;
  return {
    '@context': 'https://schema.org',
    '@type': 'BreadcrumbList',
    itemListElement: [
      {
        '@type': 'ListItem', position: 1, name: 'Home', item: `${SITE.origin}/`,
      },
      {
        '@type': 'ListItem',
        position: 2,
        name: page.breadcrumb,
        item: `${SITE.origin}${page.path}`,
      },
    ],
  };
}

const script = (data) =>
  `  <script type="application/ld+json">\n${
    JSON.stringify(data, null, 2).split('\n').map((line) => `  ${line}`).join('\n')
  }\n  </script>`;

/** The head block that replaces the source file's title and description. */
function headFor(page) {
  // A page may point its canonical at another page: /welcome does, so the
  // introduction and /how-it-works do not compete for one result.
  const target = page.canonical || page.path;
  const canonical = `${SITE.origin}${target === '/' ? '/' : target}`;
  const title = page.path === '/' ? page.title : `${page.title} | ${SITE.name}`;
  const image = `${SITE.origin}${SITE.image}`;

  const lines = [
    `  <title>${escape(title)}</title>`,
    `  <meta name="description" content="${escape(page.description)}">`,
    `  <link rel="canonical" href="${canonical}">`,
  ];

  if (page.indexable === false) {
    lines.push('  <meta name="robots" content="noindex, follow">');
  }

  lines.push(
    '',
    `  <meta property="og:type" content="website">`,
    `  <meta property="og:site_name" content="${escape(SITE.name)}">`,
    `  <meta property="og:locale" content="${SITE.locale}">`,
    `  <meta property="og:title" content="${escape(title)}">`,
    `  <meta property="og:description" content="${escape(page.description)}">`,
    `  <meta property="og:url" content="${canonical}">`,
    `  <meta property="og:image" content="${image}">`,
    `  <meta property="og:image:alt" content="${escape(SITE.imageAlt)}">`,
    '',
    `  <meta name="twitter:card" content="summary_large_image">`,
    `  <meta name="twitter:title" content="${escape(title)}">`,
    `  <meta name="twitter:description" content="${escape(page.description)}">`,
    `  <meta name="twitter:image" content="${image}">`,
    `  <meta name="twitter:image:alt" content="${escape(SITE.imageAlt)}">`,
    '',
    script(siteSchema()),
  );

  const crumbs = breadcrumbSchema(page);
  if (crumbs) lines.push(script(crumbs));

  return lines.join('\n');
}

/** index.html with the marked head block replaced by this page's. */
function render(source, page) {
  const from = source.indexOf(OPEN);
  const to = source.indexOf(CLOSE);
  if (from < 0 || to < from) {
    throw new Error(
      `public/index.html must contain ${OPEN} ... ${CLOSE} around its head tags`);
  }
  return source.slice(0, from + OPEN.length)
    + `\n${STAMP}\n${headFor(page)}\n`
    + source.slice(to);
}

function sitemap() {
  // No lastmod, changefreq or priority: they would be invented here, and
  // Google ignores the last two anyway.
  const urls = indexablePages().map((page) =>
    `  <url>\n    <loc>${SITE.origin}${page.path === '/' ? '/' : page.path}</loc>\n  </url>`);
  return '<?xml version="1.0" encoding="UTF-8"?>\n'
    + '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'
    + `${urls.join('\n')}\n</urlset>\n`;
}

function robots() {
  // Disallow is for the surfaces that are somebody's own screen, plus the
  // single-notice pages. The pages themselves also carry a noindex, which is
  // what actually removes a URL already in an index; this only saves the
  // crawl. Both are needed, and neither alone is enough.
  const disallowed = [
    ...PAGES.filter((page) => page.indexable === false).map((page) => page.path),
    '/n/',
    '/console',
  ];
  return [
    'User-agent: *',
    ...disallowed.map((path) => `Disallow: ${path}`),
    'Allow: /',
    '',
    `Sitemap: ${SITE.origin}/sitemap.xml`,
    '',
  ].join('\n');
}

export function buildSeo({ write = true } = {}) {
  const source = readFileSync(SOURCE, 'utf8');
  const files = new Map();

  for (const page of PAGES) {
    // The signed-in surfaces get a file too: without one the catch-all
    // rewrite would serve them the home page's markup, and a crawler would
    // read /dashboard as a duplicate of the home page rather than as
    // something it should leave alone.
    files.set(fileFor(page.path), render(source, page));
  }
  files.set('sitemap.xml', sitemap());
  files.set('robots.txt', robots());

  if (!write) return files;

  // Remove a generated page that is no longer in the manifest, so deleting a
  // route deletes its file rather than leaving an orphan in the sitemap's
  // absence but still served.
  const keep = new Set(files.keys());
  for (const name of readdirSync(PUBLIC)) {
    if (!name.endsWith('.html') || keep.has(name)) continue;
    const body = readFileSync(join(PUBLIC, name), 'utf8');
    if (body.includes('Generated by scripts/build-seo.mjs')) {
      unlinkSync(join(PUBLIC, name));
    }
  }

  for (const [name, body] of files) writeFileSync(join(PUBLIC, name), body);
  return files;
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const files = buildSeo();
  console.log(`Wrote ${files.size} files: ${[...files.keys()].join(', ')}`);
}
